---
core:
  - changed-files:
      - any-glob-to-any-file: platform/crates/**

ui:
  - changed-files:
      - any-glob-to-any-file: platform/apps/skillssync-desktop/ui/**

rust:
  - changed-files:
      - any-glob-to-any-file: platform/apps/skillssync-desktop/src-tauri/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "*.md"
