extends: default

rules:
  line-length:
    max: 160
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  truthy: disable

ignore: |
  platform/apps/skillssync-desktop/ui/node_modules/
